<a href="https://colab.research.google.com/github/Hepin151asodariya/Machine-Learning/blob/main/column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [ ]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["has_covid"]) , df["has_covid"],test_size=0.2)

In [ ]:
X_train
X_train.shape

(80, 5)

In [ ]:
X_test
X_test.shape

(20, 5)

In [ ]:
y_train,y_test

(8      No
 39     No
 27     No
 9      No
 14     No
      ...
 65     No
 43    Yes
 52    Yes
 20     No
 2      No
 Name: has_covid, Length: 80, dtype: object,
 99    Yes
 63     No
 24     No
 75    Yes
 70     No
 60    Yes
 38    Yes
 55    Yes
 50    Yes
 49     No
 51    Yes
 10     No
 87     No
 86    Yes
 92     No
 97     No
 47     No
 94    Yes
 4      No
 33     No
 Name: has_covid, dtype: object)

99    Yes
63     No
24     No
75    Yes
70     No
60    Yes
38    Yes
55    Yes
50    Yes
49     No
51    Yes
10     No
87     No
86    Yes
92     No
97     No
47     No
94    Yes
4      No
33     No
Name: has_covid, dtype: object

In [ ]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),["fever"]),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])],remainder="passthrough")

transformer.fit_transform(X_train).shape

(80, 7)

In [ ]:

transformer.fit_transform(X_test).shape

(20, 7)